/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet_tests;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class StrangeClassTest {

    @Test
    public void testMultiplication() {
        var expected = 33;
        var actual = StrangeClass.multiplication(11, 3);
        assertEquals(expected, actual);

        var expected2 = 14;
        var actual2 = StrangeClass.multiplication(3, 5);

        assertNotEquals(expected2, actual2);
        //assertEquals(expected2, actual2);


    }
}
